version: 0.2

env:
  variables:
    CLUSTER_NAME: sb
  parameter-store:
    ACCOUNT_ID: /sb/ACCOUNT_ID

phases:
  install:
    commands:
      - apt update -y
      - apt-get install -y docker.io

  build:
    commands:
      - aws ecr get-login-password --region ap-northeast-1 | docker login --username AWS --password-stdin ${ACCOUNT_ID}.dkr.ecr.ap-northeast-1.amazonaws.com
      - docker build -t sb .
      - docker tag sb:latest ${ACCOUNT_ID}.dkr.ecr.ap-northeast-1.amazonaws.com/sb:latest
      - docker push ${ACCOUNT_ID}.dkr.ecr.ap-northeast-1.amazonaws.com/sb:latest

  post_build:
    commands:
      - i=1
      - CURRENT_SERVICE_COUNT=`aws ecs list-services --cluster ${CLUSTER_NAME} | jq --raw-output ".serviceArns" | jq length`
      - CURRENT_SERVICES=`aws ecs list-services --cluster ${CLUSTER_NAME} | jq --raw-output ".serviceArns"`
      - |
        while [ "$i" -le "$CURRENT_SERVICE_COUNT" ]; do
          SERVICE=`echo $CURRENT_SERVICES | jq --raw-output ".[$i-1]"`
          aws ecs update-service --service ${SERVICE} --cluster ${CLUSTER_NAME} --force-new-deployment > /dev/null
          i=$(( i + 1 ))
        done
